image: maven:3.8.4-openjdk-11-slim

pipelines:
  pull-requests: 
    '**':
      - step:
          services:
            - docker
          caches:
            - docker
            - maven
          script:
            - export TESTCONTAINERS_RYUK_DISABLED=true
            - mvn clean package
  custom: # Pipelines that can only be triggered manually
    deployment-to-beta:
      - step:
          name: Build
          services:
            - docker
          caches:
            - docker
            - maven
          script:
              - apt-get update
              - apt-get install -y zip
              - export BITBUCKET_COMMIT_SHORT=$(echo $BITBUCKET_COMMIT | cut -c1-7)
              - export TESTCONTAINERS_RYUK_DISABLED=true
              - mvn clean package
              - mkdir application
              - mv target/gateway-service.jar application/gateway-service-beta-$BITBUCKET_COMMIT_SHORT.jar
              - mv appspec.yml application/appspec.yml
              - mv scripts/* application
              - cd application
              - zip -r ../application.zip *
          artifacts:
            - application.zip
      - step:
          name: Deploy to Beta
          deployment: Beta
          trigger: manual
          script:
            - pipe: atlassian/aws-code-deploy:0.5.2
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: 'ap-southeast-1'
                S3_BUCKET: 'b3-build-artifacts'
                APPLICATION_NAME: 'gateway-service'
                COMMAND: 'upload'
                ZIP_FILE: 'application.zip'
            - pipe: atlassian/aws-code-deploy:0.5.2
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: 'ap-southeast-1'
                S3_BUCKET: 'b3-build-artifacts'
                COMMAND: 'deploy'
                APPLICATION_NAME: 'gateway-service'
                DEPLOYMENT_GROUP: 'beta'
                WAIT: 'true'
                FILE_EXISTS_BEHAVIOR: 'OVERWRITE'
  branches:
    develop:
      - step:
          name: Build
          services:
            - docker
          caches:
            - docker
            - maven
          script:
              - apt-get update
              - apt-get install -y zip
              - export BITBUCKET_COMMIT_SHORT=$(echo $BITBUCKET_COMMIT | cut -c1-7)
              - export TESTCONTAINERS_RYUK_DISABLED=true
              - mvn clean package
              - mkdir application
              - mv target/gateway-service.jar application/gateway-service-alpha-$BITBUCKET_COMMIT_SHORT.jar
              - mv appspec.yml application/appspec.yml
              - mv scripts/* application
              - cd application
              - zip -r ../application.zip *
          artifacts:
            - application.zip
      - step:
          name: Deploy to Alpha
          deployment: Alpha
          trigger: automatic
          script:
            - pipe: atlassian/aws-code-deploy:0.5.2
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: 'ap-southeast-1'
                S3_BUCKET: 'b3-build-artifacts'
                APPLICATION_NAME: 'gateway-service'
                COMMAND: 'upload'
                ZIP_FILE: 'application.zip'
            - pipe: atlassian/aws-code-deploy:0.5.2
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: 'ap-southeast-1'
                S3_BUCKET: 'b3-build-artifacts'
                COMMAND: 'deploy'
                APPLICATION_NAME: 'gateway-service'
                DEPLOYMENT_GROUP: 'alpha'
                WAIT: 'true'
                FILE_EXISTS_BEHAVIOR: 'OVERWRITE'
    master:
      - step:
          name: Build
          services:
            - docker
          caches:
            - docker
            - maven
          script:
              - apt-get update
              - apt-get install -y zip
              - export BITBUCKET_COMMIT_SHORT=$(echo $BITBUCKET_COMMIT | cut -c1-7)
              - export TESTCONTAINERS_RYUK_DISABLED=true
              - mvn clean package
              - mkdir application
              - mv target/gateway-service.jar application/gateway-service-release-$BITBUCKET_COMMIT_SHORT.jar
              - mv appspec.yml application/appspec.yml
              - mv scripts/* application
              - cd application
              - zip -r ../application.zip *
          artifacts:
            - application.zip
      - step:
          name: Deploy to Production
          deployment: Prod
          trigger: manual
          script:
            - pipe: atlassian/aws-code-deploy:0.5.2
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: 'ap-southeast-1'
                S3_BUCKET: 'b3-build-artifacts'
                APPLICATION_NAME: 'gateway-service'
                COMMAND: 'upload'
                ZIP_FILE: 'application.zip'
            - pipe: atlassian/aws-code-deploy:0.5.2
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: 'ap-southeast-1'
                S3_BUCKET: 'b3-build-artifacts'
                COMMAND: 'deploy'
                APPLICATION_NAME: 'gateway-service'
                DEPLOYMENT_GROUP: 'prod'
                WAIT: 'true'
                FILE_EXISTS_BEHAVIOR: 'OVERWRITE'