version: "3.7"
services:
  eureka-server:
    container_name: eureka-server
    image:  eureka-service-image
    hostname: eureka-server
    networks:
      - ms-network
    ports:
      - 8761:8761 
    environment:
      eureka.instance.hostname: eureka-server
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka

  order_service:
    container_name: order-service
    image: order-service-image
    build: .
    restart: always
    ports:
      - 8763:8763
    links:
      - eureka-server
    environment:
      spring.datasource.url: jdbc:mysql://mysqldb:3306/order_schema?allowPublicKeyRetrieval=true 
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka
    networks:
      - ms-network
    depends_on:
      - mysqldb
      - eureka-server
    volumes:
      - .m2:/root/.m2

  product_service:
    container_name: product-service
    image: product-service-image
    build: .
    restart: always
    ports:
      - 8762:8762
    links:
      - eureka-server
    environment:
      spring.datasource.url: jdbc:mysql://mysqldb:3306/product_schema?allowPublicKeyRetrieval=true 
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka
    networks:
      - ms-network
    depends_on:
      - mysqldb
      - eureka-server
    volumes:
      - .m2:/root/.m2

  payment_service:
    container_name: payment_service
    image: payment-service-image
    build: .
    restart: always
    ports:
      - 8764:8764
    links:
      - eureka-server
    environment:
      spring.datasource.url: jdbc:mysql://mysqldb:3306/payment_schema?allowPublicKeyRetrieval=true 
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka
    networks:
      - ms-network
    depends_on:
      - mysqldb
      - eureka-server
    volumes:
      - .m2:/root/.m2

  user_service:
    container_name: user_service
    image: user-service-image
    build: .
    restart: always
    ports:
      - 8765:8765
    links:
      - eureka-server
    environment:
      spring.datasource.url: jdbc:mysql://mysqldb:3306/user_schema?allowPublicKeyRetrieval=true 
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka
    networks:
      - ms-network
    depends_on:
      - mysqldb
      - eureka-server
    volumes:
      - .m2:/root/.m2

  gateway_service:
    container_name: api-gateway-service
    image: gateway-service-image
    build: .
    restart: always
    ports:
      - 8769:8769
    links:
      - eureka-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka
    networks:
      - ms-network
    depends_on:
      - eureka-server

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - ms-network
      
  mysqldb:
    image: "mysql:8.2"
    restart: always
    ports:
      - 3306:3306
    networks:
      - ms-network
    environment:
      MYSQL_DATABASE: order_schema
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:

networks:  
  ms-network:  
    name: ms-network  
    driver: bridge
