server:
  servlet:
    context-path: /
  port: 8080

spring:
  profiles:
    active:
      - ${YODA_SPRING_PROFILE:dev}
  application:
    name: gateway-service

# Disable auto cloud formation
cloud:
  aws:
    stack:
      auto: false
---

spring:
  profiles: dev
jwt:
  secret: n2r5u8x/A%D*G-KaPdSgVkYp3s6v9y$B&E(H+MbQeThWmZq4t7w!z%C*F-J@NcRf
  expiration: 31536000000

linkid:
  client-id:
  client-secret:

jwks:
  url:
   pre-prod: https://preprod-auth.fairprice.com.sg/
   prod: https://auth.fairprice.com.sg/
claims:
  identity:
    uid: https://claims.identity.nedigital.sg/uid
    associationId: https://claims.identity.nedigital.sg/association/health
    audience: https://api.app.ntuchealth.cloud

link-bridge:
  url:
    token: https://preprod-m2mauth.nedigital.sg/oauth/token
    api: https://preprod-identity.nedigital.sg

---

spring:
  profiles: alpha, uat, prod



