server:
  servlet:
    context-path: /
  port: 8080

spring:
  profiles:
    active:
      - ${BUMBLEBEE_SPRING_PROFILE:dev}
  application:
    name: gateway-service

# Disable auto cloud formation
cloud:
  aws:
    stack:
      auto: false

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: Gateway Service
        primaryName: Gateway Service
      - url: /profile-service/v3/api-docs
        name: Profile Service
        primaryName: Profile Service
---

spring:
  profiles: dev
jwt:
  secret: n2r5u8x/A%D*G-KaPdSgVkYp3s6v9y$B&E(H+MbQeThWmZq4t7w!z%C*F-J@NcRf
  expiration: 31536000000

linkid:
  client-id: ${BUMBLEBEE_LINKEDID_CLIENT_ID}
  client-secret: ${BUMBLEBEE_LINKEDID_CLIENT_SECRET}

jwks:
  url: https://preprod-auth.fairprice.com.sg/
claims:
  identity:
    uid: https://claims.identity.nedigital.sg/uid
    associationId: https://claims.identity.nedigital.sg/association/health
    audience: https://api.app.ntuchealth.cloud

link-bridge:
  url:
    token: https://preprod-m2mauth.nedigital.sg/oauth/token
    api: https://preprod-identity.nedigital.sg

redis:
  host: localhost
  port: 6379

openapi:
  service:
    gateway-url: https://api.alpha.app.ntuchealth.cloud

---
spring:
  profiles: alpha

openapi:
  service:
    gateway-url: https://api.alpha.app.ntuchealth.cloud
---
spring:
  profiles: uat

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

---
spring:
  profiles: prod

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

---
sns:
  topic:
    application-analytics-event: dev-application-analytics-event-topic
